language: node_js
node_js:
  - "0.10"
  - "0.12"

notifications:
  email:
    - johnny.estilles@agentia.asia

addons:
 code_climate:
   repo_token: 636ae2cc82f862714a33f273378aa1699e355c78ee10353e288efc2c59386d60

before_install:
  - npm install -g codeclimate-test-reporter

after_script:
  - npm run cover
  - codeclimate < ./coverage/lcov.info

branches:
  only:
    - master
